[project]
name = "catppuccin-zensical"
version = "0.2.3"
description = "Catppuccin theme extension for Zensical"
readme = "README.md"
authors = [
    { name = "jonathan343", email = "jonathangee09@gmail.com" }
]
license = "MIT"
requires-python = ">=3.10"
dependencies = [
    "zensical>=0.0.37",
]
keywords = [
    "catppuccin",
    "documentation",
    "theme",
    "zensical",
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Topic :: Documentation",
]

[project.urls]
"Changelog" = "https://github.com/jonathan343/catppuccin-zensical/blob/main/CHANGELOG.md"
"Code" = "https://github.com/jonathan343/catppuccin-zensical"
"Documentation" = "https://jonathan343.github.io/catppuccin-zensical/"
"Issue tracker" = "https://github.com/jonathan343/catppuccin-zensical/issues"

# Zensical uses this entry point group to discover installed themes.
[project.entry-points."mkdocs.themes"]
catppuccin = "catppuccin_zensical"

[build-system]
requires = ["uv_build>=0.11.8,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "jmeslog>=0.2.0",
]
docs = [
    "zensical>=0.0.37",
]
